### ISSUE TITLE
Naming of integrals.

### ISSUE THREAD

**Issue by lang-m** [ubermag/discretisedfield#112]
Currently an integral like `$\int dx' f(x') = F(x)$` can be computed with `improper=True`. This is not the correct name (https://mathworld.wolfram.com/ImproperIntegral.html). Instead we should use `indefinite=True` (https://mathworld.wolfram.com/IndefiniteIntegral.html).

**Comment by marijanbeg** [comment]
Hi @lang-m, I think neither of those two is what we have, but I agree indefinite is "closer" than improper.

Mathematically speaking, what we are calculating here is the convolution of a field with a Heaviside function. I guess if we want to be strict, this should not be part of `df.integral`. Is the convolution functionality you did for counting BPs in `df` or it lives in your notebooks?

**Comment by lang-m** [comment]
Some ideas for new integral syntax
```python
tcd = df.Field(...)

(tcd * df.dV).integral('yz').integral('x', improper=True)
((tcd * df.dx * df.dy).integral('yz') * df.dx).integral('x', improper=True)
((tcd * df.dx * df.dy).integral() * df.dx).integral(improper=True)

tcd.integral(('dx', improper=True), 'dy', 'dz')
tcd.integral(('dx', 'improper'), 'dy', 'dz')

###

tcd.integral(('dx', improper=True), ['dS', dot_product=True])
tcd.integral(('dx', 'improper'), ['dS', 'dot'])
tcd.integral(('dx', 'improper'), '@dS')

(tcd @ df.dS).integral()
tcd.integral('@dS')   # ∫ dx dy f • ez

(tcd & df.dS).integral()
tcd.integral('&dS')   # ∫ dx dy f × ez

(tcd * df.dS).integral()
tcd.integral('dS')    # ∫ dx dy f

tcd.integral(('dS', 'dot_product'))
tcd.integral(('dot', 'dS'))
tcd.integral(('dS', dot_product=True))
```

**Comment by lang-m** [comment]
Done in #204
