### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by KevinYanesG** [ubermag/discretisedfield#167]
First things first: The documentation is great and very comprehensive! Well done!

I've found some small errors that I will list in the following. If you agree with it, and after you give the corresponding feedback, I would be happy to correct the errors myself by opening a MR.

I will highlight the titles of the corresponding pages of the documentation

**mesh basics**
The functionality of `mesh.n` is showed twice, but maybe this was intended.
100 small cubes? or should it be 10?
![image](https://user-images.githubusercontent.com/75472729/185648479-d2b897cf-f24b-43e2-bd51-d32d24be29c3.png)

are these the coordinates or the indices of the neighbouring cells?
![image](https://user-images.githubusercontent.com/75472729/185648934-ffef9deb-0f76-4e7e-89aa-60b8978ded6c.png)

**mesh subregions**
This gives a lot of freedom to users on how they can define the subregions, but also some responsibilities.
![image](https://user-images.githubusercontent.com/75472729/185649065-f03283ca-e803-4b6a-9d84-9f5ef181b58e.png)

color tuple?
![image](https://user-images.githubusercontent.com/75472729/185649136-476740f5-cc19-4942-bfa4-c2a056c8f28d.png)

**mesh pad:**
intended to be a one-liner? or should it be a list
![image](https://user-images.githubusercontent.com/75472729/185649212-f6b1d2b9-dde9-4fd2-99c9-9e8af10c4974.png)

**holoviews**
doesn't update in the web version, but I guess this is on purpose, because it is a DynamicMap? maybe one hint for the webusers at the beginning of the tutorial?
![image](https://user-images.githubusercontent.com/75472729/185649537-66d5febf-2dcf-4e01-a52b-8e931289703c.png)

All the other things that I've listed are small typing errors that I would correct directly on the MR.

Best regards

**Comment by lang-m** [comment]
Thanks for your feedback. Feel free to open a PR and fix these issues.

**Comment by KevinYanesG** [comment]
Are you going to update your docs due to the newer changes on the code? Should I wait to correct this? Or should I do it now?

**Comment by fangohr** [comment]
I would correct the docs for the current behaviour now. 

Updates to the documentation should be in the same merge request as the interface  changes. (Our CI is also testing the docs.)
