### ISSUE TITLE
Scale and translate in Mesh

### ISSUE THREAD

**Issue by lang-m** [ubermag/discretisedfield#206]
Currently, we have added scale and translate for Region. This could be done in-place for a mesh defined on a Region:
```python
mesh.region.scale(3, inplace=True)
```

However, it would not change subregions that might be defined for the mesh. I think it would be good to add `scale` and `translate` to the mesh to translate/scale both the region and all subregions (if defined).

Thoughts @samjrholt , @swapneelap ?

**Comment by samjrholt** [comment]
@lang-m I agree, I think mesh should have its own method which deals with all of the relevant parts of mesh properly.

**Comment by swapneelap** [comment]
@lang-m sounds good to me. I can add them in the refactor mesh PR or do we want to do this saperately?

**Comment by lang-m** [comment]
We can do it in the refactor mesh PR.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
