### ISSUE TITLE
Remove or update python package dependencies

### ISSUE THREAD

**Issue by Vrekrer** [ubermag/discretisedfield#372]
Latest version of jupyterlab is 4.0.2

Is this dependency really needed?
`jupyterlab~=3.0`

Same problem in ubermagtable.

**Comment by lang-m** [comment]
Hi @Vrekrer, we will relax this restriction in the next release. If you need any of the new features of jupyterlab 4 in the mean time, you should be able to install jupyterlab 4 in a separate environment and create a custom kernel for your ubermag environment.
