### ISSUE TITLE
Check `mesh.mpl.subregions`

### ISSUE THREAD

**Issue by lang-m** [ubermag/discretisedfield#379]
The code will use `region.mpl` which applies automatic scaling if nothing else is specified. Check the behaviour for a mesh containing multiple subregions in different parts of the region that require rescaling. I assume that this will produce the wrong output because of the scaling centre defaulting to the (sub)region centre point.

If my assumption is correct we have to rescale subregions first and plot them afterwards (with scaling disabled). I would suggest to scale with respect to the region size and region centre.

**Comment by swapneelap** [comment]
Hello @lang-m, I am not sure if I fully understand your point. Are you talking about the plots of the sub-regions when one scales the mesh?

**Comment by samjrholt** [comment]
I have checked and we always scale about the same reference point of the origin for plotting in both `mesh.mpl()` and `mesh.mpl.subplots()`. I have also tested this and it has the correct behavior.
