### ISSUE TITLE
On the value of discretisedfield

### ISSUE THREAD

**Issue by code-whale** [ubermag/discretisedfield#74]
Dear Ubermag team,
  I encountered a problem in simulating a multilayer structure. I don't know what it means to define a three-dimensional value in field. I don't know if I rely on this value and norm=Ms to determine the initial magnetic moment distribution of this material. There is a non-magnetic layer in the multilayer structure that I simulate. How should I define its value for this non-magnetic region?
  I define the value of field through the following figure function, but when I am creating field, the program reports an error. How can I solve this problem to achieve the desired results?
![image](https://user-images.githubusercontent.com/61874432/85921782-3ff58a80-b8b1-11ea-8c8c-2da60e4c6fd3.png)
![image](https://user-images.githubusercontent.com/61874432/85921787-484dc580-b8b1-11ea-94f9-9f6456af80d1.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, if the value of a vector field is (0, 0, 0), it cannot be normalised. Mathematically, it does not make sense to set up the length of a zero-vector. The regions of the mesh you want to set the norm to be 0, you need to do that using `norm` and not `value`.

**Comment by code-whale** [comment]
Another question I would like to ask is whether the definition of filed defines the initial state of the simulated material without any energy or dynamics, using the vector direction of value to represent the magnetic moment distribution and norm to represent the saturation magnetization.

**Comment by marijanbeg** [comment]
That is correct. In micromagnetics, we are basically solving an initial value problem. As the name says, we must have an initial state defined, from which we start the time-integration.

**Comment by code-whale** [comment]
I think my problem has been solved. Thank you for your patient and detailed answer.

**Comment by code-whale** [comment]
I'm sorry. I have one more question to ask you. 
When I set the spatial variation A, the material I simulated has a negative interlayer exchange constant was set as −10 pJ/m
  But when I use the example syntax to define the energy item, the program saves that An is not allowed to be negative. How to deal with this situation?

**Comment by marijanbeg** [comment]
I think we addressed this issue in the last session and tutorial is available on this topic in workshop repository.

(Please make sure you reopen issue when you have further questions, so we know we need to address it.)

**Comment by code-whale** [comment]
Thank you for your help. I learned the tutorial, and now I know how to set it up.

**Comment by marijanbeg** [comment]
Great!
