### ISSUE TITLE
Update binder button / link

### ISSUE THREAD

**Issue by fangohr** [ubermag/discretisedfield#96]
- the binder button link on https://github.com/ubermag/discretisedfield points to https://mybinder.org/v2/gh/ubermag/discretisedfield/stable?filepath=docs%2Fipynb%2Findex.ipynb . This fails; I am guessing because there is no docs/index.ipynb?

- if the binder environment is created directly (for example through https://mybinder.org/v2/gh/ubermag/discretisedfield/stable), running tests fails because scipy is not in the requirements:
   <img width="986" alt="Screenshot 2021-09-22 at 21 47 31" src="https://user-images.githubusercontent.com/4489119/134412287-cec4942d-da04-4b91-b3de-173b07b25730.png">

**Comment by lang-m** [comment]
The path `docs/ipynb/index.ipynb` does exist. The problem of the broken link seems to be related to Binder opening Jupyter Notebook and not Jupyter lab (what we want it to do). The new default (https://discourse.jupyter.org/t/mybinder-org-using-jupyterlab-by-default/10715) does not seem to work properly (or is somehow incompatible with specifying a notebook).
@fangohr could you please try this link: https://mybinder.org/v2/gh/ubermag/discretisedfield/stable?urlpath=lab/tree/docs/ipynb/index.ipynb

**Comment by lang-m** [comment]
Missing `scipy` is fixed.

**Comment by lang-m** [comment]
All links are now updated.
